# catalog_parser.py
# Parses dbt catalog.json and extracts column types and row counts.
# Returns a dictionary keyed by model name containing
# column type information and row counts for each materialised model.
#
# Source: target/catalog.json
# Generated by: dbt docs generate
#
# _preprocess filters to model nodes only and strips index from columns
# _parse_file extracts column types, row counts, and descriptions

import logging
from .base_parser import BaseParser

logger = logging.getLogger(__name__)


class CatalogParser(BaseParser):

    def _cache_name(self) -> str:
        return 'catalog'

    def _preprocess(self, data: dict) -> dict:
        # keep only model nodes — discard seeds, tests, snapshots
        # strip index from each column — position not needed
        return {
            'nodes': {
                key: {
                    'metadata': node.get('metadata', {}),
                    'columns': {
                        col_name: {
                            'type': col.get('type', ''),
                            'name': col.get('name', ''),
                            'comment': col.get('comment')
                        }
                        for col_name, col in node.get(
                            'columns', {}
                        ).items()
                    }
                }
                for key, node in data.get('nodes', {}).items()
                if key.startswith('model.')
            }
        }

    def _parse_file(self, data: dict) -> dict:
        catalog = {}
        nodes = data.get('nodes', {})

        for key, node in nodes.items():
            # extract model name from full node key
            # e.g. 'model.jaffle_shop.orders' → 'orders'
            model_name = node.get('metadata', {}).get('name', '')
            if not model_name:
                model_name = key.split('.')[-1]

            logger.info(f"Parsing catalog node: {model_name}")

            # extract column information
            columns = {
                col_name: {
                    'type': col.get('type', ''),
                    'description': col.get('comment') or ''
                }
                for col_name, col in node.get('columns', {}).items()
            }

            catalog[model_name] = {
                'row_count': node.get(
                    'metadata', {}
                ).get('row_count'),
                'materialization': node.get(
                    'metadata', {}
                ).get('type', ''),
                'schema': node.get(
                    'metadata', {}
                ).get('schema', ''),
                'columns': columns
            }

        logger.info(f"Parsed {len(catalog)} models from catalog")
        return catalog