# manifest_parser.py
# Parses dbt manifest.json and extracts model metadata.
# Returns a dictionary keyed by model name containing
# all fields needed to enrich TableMetadata objects.
#
# Source: target/manifest.json
# Generated by: dbt compile, dbt run, dbt docs generate
#
# _preprocess filters to model nodes only and keeps child_map
# _parse_file extracts structured metadata from each model node

import logging
from .base_parser import BaseParser

logger = logging.getLogger(__name__)


class ManifestParser(BaseParser):

    def _cache_name(self) -> str:
        return 'manifest'

    def _preprocess(self, data: dict) -> dict:
        # keep only model nodes — discard tests, seeds, snapshots,
        # exposures, macros. reduces memory before parsing.
        # keep child_map filtered to model-to-model relationships only
        model_keys = {
            key for key, node in data.get('nodes', {}).items()
            if node.get('resource_type') == 'model'
        }

        return {
            'nodes': {
                key: node
                for key, node in data.get('nodes', {}).items()
                if key in model_keys
            },
            'child_map': {
                key: [
                    child for child in children
                    if child.startswith('model.')
                ]
                for key, children in data.get('child_map', {}).items()
                if key in model_keys
            }
        }

    def _parse_file(self, data: dict) -> dict:
        models = {}
        nodes = data.get('nodes', {})
        child_map = data.get('child_map', {})

        for key, node in nodes.items():
            model_name = node['name']
            logger.info(f"Parsing manifest node: {model_name}")

            # extract column descriptions
            column_descriptions = {
                col_name: col.get('description', '')
                for col_name, col in node.get('columns', {}).items()
            }

            # extract immediate upstream lineage — model names only
            # strip the full node key e.g. 'model.jaffle_shop.orders'
            # to just the model name e.g. 'orders'
            raw_lineage = node.get('depends_on', {}).get('nodes', [])
            lineage = [
                n.split('.')[-1] for n in raw_lineage
                if n.startswith('model.')
            ]

            # compute documentation health
            all_columns = node.get('columns', {})
            documented_columns = sum(
                1 for col in all_columns.values()
                if col.get('description', '').strip()
            )
            total_columns = len(all_columns)
            documented_pct = (
                round(documented_columns / total_columns * 100, 1)
                if total_columns > 0 else 0.0
            )

            # compute relationship counts
            # upstream — number of models this model depends on
            upstream_count = len(lineage)

            # downstream — number of models that depend on this one
            # child_map contains all dependents including tests
            # filter to model dependents only
            downstream_count = sum(
                1 for child in child_map.get(key, [])
                if child.startswith('model.')
            )

            models[model_name] = {
                'description': node.get('description', ''),
                'lineage': lineage,
                'materialization': node.get(
                    'config', {}
                ).get('materialized', ''),
                'owner': node.get(
                    'config', {}
                ).get('meta', {}).get('owner', ''),
                'tags': node.get('tags', []),
                'column_descriptions': column_descriptions,
                'has_description': bool(
                    node.get('description', '').strip()
                ),
                'columns_documented_pct': documented_pct,
                'upstream_count': upstream_count,
                'downstream_count': downstream_count,
            }

        logger.info(f"Parsed {len(models)} models from manifest")
        
        return models